backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/blog"
public_folder: "/assets/blog"
collections: 
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "mySlug", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: "false" }
      - { label: "Author", name: "author", widget: "string", required: "false" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"], required: "false" }
      - { label: "Featured Image", name: "image", widget: "image", required: "false" }
      - { label: "Alt Text", name: "imageAlt", widget: "string", required: "false" }
      - { label: "Body", name: "body", widget: "markdown" }